### ISSUE TITLE
TODO updates

### ISSUE THREAD

**Issue by jeremylumanbailey** [jeremylumanbailey/minecraftautoshutdown#1]
- [ ]  The module used 'mc-ping-updated' is [deprecated](https://www.npmjs.com/package/mc-ping-updated).
Needs to be updated to use [mcping-js](https://www.npmjs.com/package/mcping-js) instead.

- [ ] #2

- [ ] Want to add some kind of env json so time variable and shutdown commands are not hard coded into the code.

- [ ] Add windows support 

- [ ] Add README.md with instructions on setup and how to use [pm2](https://pm2.keymetrics.io/docs/usage/quick-start/) to startup server on computer startup.

General links used:

- [Setting up minecraft server on ec2](https://raibledesigns.com/rd/entry/setting_up_a_minecraft_server)
- [Hours to miliseconds converter](http://www.kylesconverter.com/time/hours-to-milliseconds)
- [Deploying node application to AWS EC2 instance](https://hackernoon.com/deploying-a-node-app-on-amazon-ec2-d2fb9a6757eb)
